version: "3.6"
services:
  postgres:
    image: postgres:16
    ports:
      - ${PGPORT:-5432}:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb.d-postgres:/docker-entrypoint-initdb.d:ro
  graphql-engine:
    image: hasura/graphql-engine:v2.37.0.cli-migrations-v3
    ports:
      - ${HGEPORT:-8080}:8080
    restart: always
    environment:
      HASURA_GRAPHQL_DEV_MODE: true
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: true
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    volumes:
      - ./metadata:/hasura-metadata:ro
    depends_on:
      - postgres

